# syntax=docker/dockerfile:1

# Define base docker image to start
FROM node:14.15.1 AS base

# Maintained by:
LABEL maintainer="navedsr@yahoo.com"

# Define working directory for applications
WORKDIR /app

# Copy configuration files to docker image
COPY ["package.json", "package-lock.json*", "./"]

# Copy application files to docker image
COPY . .

# Install packages
RUN npm install

# Run npm package
CMD [ "npm", "start" ]

