name: Docker Image CI-CD (Production)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.prod --tag prod:$(date +%s)

    - name: Push the Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: navedsr/mmtcarsunlimited:prod
        tag_with_ref: true
